wandb_version: 1

bs:
  desc: null
  value: 12
_wandb:
  desc: null
  value:
    python_version: 3.9.13
    cli_version: 0.14.2
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1681675472.38129
    t:
      1:
      - 1
      - 2
      - 3
      - 55
      2:
      - 1
      - 2
      - 3
      - 55
      3:
      - 7
      - 16
      - 23
      - 38
      4: 3.9.13
      5: 0.14.2
      8:
      - 3
      - 5
    m:
    - 1: epoch/epoch
      6:
      - 3
    - 1: epoch/loss
      5: 1
      6:
      - 1
    - 1: epoch/accuracy
      5: 1
      6:
      - 1
    - 1: epoch/val_loss
      5: 1
      6:
      - 1
    - 1: epoch/val_accuracy
      5: 1
      6:
      - 1
    - 1: epoch/learning_rate
      5: 1
      6:
      - 1
